config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
    
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  get "users/new"
  
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope order: 'microposts.created_at DESC'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
                                     class_name:  "Relationship",
                                     dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
                                            uniqueness: {case_sensitive: true}
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
    
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy
  
  def index
  end
    
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
      @micropost.destroy
      redirect_to root_url
  end
  
  private

     def correct_user
       @micropost = current_user.microposts.find_by_id(params[:id])
       redirect_to root_url if @micropost.nil?
     end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :signed_in_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_back_or user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
     end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy 
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # Handle a successful update.
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index 
    @users = User.paginate(page: params[:page])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
    
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
    
  private 
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      "#{base_title}"
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
     @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
    
  def destroy
    sign_out
    redirect_to root_url
  end
    
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
	%small
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
		
	%nav
		%ul
			%li= link_to "About",   '#' 
			%li= link_to "Contact", '#'
			%li <a href="http://news.railstutorial.org/">News</a>

app/views/layouts/_header.html.haml
%header.navbar-fixed-top.navbar-inverse
	.navbar-inner
		.container
			= link_to "sample app", '#', id: "logo"
			%nav
				%ul.nav.pull-right
					%li= link_to "Home", root_path
					%li= link_to "Help", help_path
					- if signed_in? 
						%li= link_to "Users", users_path
						%li#fat-menu.dropdown
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							%ul.dropdown-menu
								%li= link_to "Profile", current_user
								%li= link_to "Settings", edit_user_path(current_user)
								%li.divider
								%li= link_to "Sign out", signout_path, method: "delete"
					- else 
						%li= link_to "Sign in", signin_path
					

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title= "#{full_title(yield(:title))}"
		= stylesheet_link_tag "application", :media => "all" 
		= javascript_include_tag "application" 
		= csrf_meta_tags 
		= render 'layouts/shim'
	%body
		= render 'layouts/header'
		.container
			- flash.each do |key, value|
				.alert{:class => "alert-#{key}"}= value
			= yield
			= render 'layouts/footer'
			= debug(params) if Rails.env.development?

app/views/microposts/_micropost.html.haml
%li
	%span.content 
		= micropost.content
	%span.timestamp
		Posted 
		= time_ago_in_words(micropost.created_at)  
		ago.
		- if current_user?(micropost.user)
			= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" }, title: micropost.content

app/views/shared/_error_messages.html.haml
-if object.errors.any?
	#error_explanation
		.alert.alert-error
			The form contains 
			= pluralize(object.errors.count, "error")
		%ul
			- object.errors.full_messages.each do |msg|
				%li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
	%ol.microposts
		= render partial: 'shared/feed_item', collection: @feed_items
	= will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%li{ :id => feed_item.id }
	= link_to gravatar_for(feed_item.user), feed_item.user
	%span.user
		= link_to feed_item.user.name, feed_item.user
	%span.content= feed_item.content
	%span.timestamp
		Posted
		= time_ago_in_words(feed_item.created_at)
		ago.
		- if current_user?(feed_item.user)
			= link_to "delete", feed_item, method: :delete, data: { confirm: "You sure?" }, title: feed_item.content

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
	= render 'shared/error_messages', object: f.object
	.field
		= f.text_area :content, placeholder: "Compose new micropost..."
	= f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => following_user_path(@user)}
    %strong#following.stat
      = @user.followed_users.count
    following
  %a{:href => followers_user_path(@user)}
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user), user_path(current_user)
%h1
  = current_user.name
%span
  = link_to "view my profile", current_user
%span
  = pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    	<h1>About Us</h1>
	    <p>
	      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	      is a project to make a book and screencasts to teach web development
	      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
	      is the sample application for the tutorial.
	    </p>

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%h1 About Us
%p
	The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	is a project to make a book and screencasts to teach web development
	with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
	is the sample application for the tutorial.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
	Contact Ruby on Rails Tutorial about the sample app at the
	<a href="http://railstutorial.org/contact">contact page</a>.

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/help.html.haml
- provide(:title, 'Help') 
%h1 Help
%p
	Get help on the Ruby on Rails Tutorial at the
	<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
	<a href="http://railstutorial.org/book">Rails Tutorial book</a>.

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
    <h1>Sample App</h1>
    <p>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>

app/views/static_pages/home.html.haml
- if signed_in?
	.row
		%aside.span4
			%section
				= render 'shared/user_info'
			%section
				= render 'shared/stats'
			%section
				= render 'shared/micropost_form'
	.span8
		%h3 Micropost Feed
		= render 'shared/feed'
- else
	.center.hero-unit
		%h1 Sample App
		%h2
			This is the home page for the
			<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
			sample application.

		= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" 

	= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| 
	%div= f.hidden_field :followed_id
	= f.submit "Follow", class: "btn btn-large btn-primary"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.find_by_followed_id(@user),html: { method: :delete }) do |f|
	= f.submit "Unfollow", class: "btn btn-large"

app/views/users/_user.html.haml
%li
	= gravatar_for user
	= link_to user.name, user
	- if current_user.admin? && !current_user?(user)
		= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.haml
- provide(:title, "Edit user") 
%h1 Update your profile

.row
	.span6.offset3
		= form_for(@user) do |f|
			= render 'shared/error_messages', object: f.object

			= f.label :name
			= f.text_field :name

			= f.label :email
			= f.text_field :email

			= f.label :password
			= f.password_field :password

			= f.label :password_confirmation, "Confirm Password"
			= f.password_field :password_confirmation

			= f.submit "Save changes", class: "btn btn-large btn-primary"

		= gravatar_for @user
		<a href="http://gravatar.com/emails">change</a>

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users

= will_paginate

%ul.users
	= render @users
			
= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
.row
	.span6.offset3
		= form_for(@user) do |f|
			= render 'shared/error_messages', object: f.object
			= f.label :name 
			= f.text_field :name 
			= f.label :email 
			= f.text_field :email 
			= f.label :password 
			= f.password_field :password 
			= f.label :password_confirmation, "Confirmation" 
			= f.password_field :password_confirmation 
			= f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
	%aside.span4
		%section
			%h1
				= @user.name
				= gravatar_for @user
	.span8
		= render 'follow_form' if signed_in?
		- if @user.microposts.any?
			%h3= "Microposts (#{@user.microposts.count})"
			%ol.microposts
				= render @microposts
			= will_paginate @microposts

app/views/users/show_follow.html.haml
- provide(:title, @title)
.row
  %aside.span4
    %section
      = gravatar_for @user
      %h1= @user.name
      %span= link_to "view my profile", @user
      %span
        %b Microposts:
        = @user.microposts.count
    %section
      = render 'shared/stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  .span8
    %h3= @title
    - if @users.any?
      %ul.users
        = render @users
      = will_paginate